In [1]:
#multiple decision tree are created during a traing phase
#slower then decision tree
#majority base predict a value
#after prediction data got like ...drug A, drug A, drug A,drug B, then entropy will low,information gain is high
# and less impurity and accuracy is high
#

In [2]:
#import packages
import pandas as pd
import numpy as np
import scipy.optimize as opt
import pylab as pl
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv("C:/Users/user/Inside_march/Mar/regression/updatefile/RandomFORest/Social_Network_Ads.csv")

df.head(15)

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
5   15728773    Male   27            58000          0
6   15598044  Female   27            84000          0
7   15694829  Female   32           150000          1
8   15600575    Male   25            33000          0
9   15727311  Female   35            65000          0
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [6]:
x=df[['Age','EstimatedSalary']].values
x[0:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]], dtype=int64)

In [7]:
y=df[['Purchased']]
y[0:5]

Purchased
0          0
1          0
2          0
3          0
4          0

In [8]:
#train_test_split dataset 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=4)
print("train",x_train.shape, y_train.shape)
print("test",x_test.shape,y_test.shape)

train (300, 2) (300, 1)
test (100, 2) (100, 1)


In [9]:
#data processing into standard scaler

from sklearn import preprocessing
x=preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059]])

In [10]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print("train",x_train)
print("test",x_test)

train [[-1.04188331e+00 -1.46549006e+00]
 [-6.63704251e-01  1.66393881e-01]
 [-1.70369667e+00  4.57801728e-01]
 [ 1.98354917e+00 -8.24392800e-01]
 [ 1.41628058e+00  3.41238589e-01]
 [ 1.32173582e+00 -9.40955939e-01]
 [-2.85525191e-01 -9.11815155e-01]
 [ 9.43556756e-01 -1.02837829e+00]
 [-9.47338546e-01 -1.11580065e+00]
 [ 1.98354917e+00  2.11882646e+00]
 [ 1.03810152e+00 -9.99237509e-01]
 [-2.85525191e-01 -5.91266522e-01]
 [ 5.65377695e-01  2.00226332e+00]
 [-1.42006237e+00 -1.46549006e+00]
 [-1.13642808e+00  4.98307419e-02]
 [ 1.79445964e+00 -2.99858675e-01]
 [-2.85525191e-01  4.98307419e-02]
 [ 1.22719105e+00  2.20624881e+00]
 [ 9.43556756e-01  1.08112311e-01]
 [-8.52793781e-01 -1.23236379e+00]
 [-9.47338546e-01 -7.66111231e-01]
 [-3.80069956e-01 -7.95252016e-01]
 [-9.64356604e-02 -2.41577106e-01]
 [-2.85525191e-01  6.03505652e-01]
 [ 1.41628058e+00  2.11882646e+00]
 [-1.13642808e+00  3.12097805e-01]
 [ 9.26538698e-02  2.06899572e-02]
 [-1.89089530e-03 -2.70717890e-01]
 [ 3.76288165e

In [11]:
#modeling 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=4)
classifier

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=4, verbose=0,
                       warm_start=False)

In [12]:
#fit the question and answer
classifier.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=4, verbose=0,
                       warm_start=False)

In [13]:
#predict
predi=classifier.predict(x_test)
predi

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [14]:
#find the acuracy
from sklearn.metrics import f1_score
print("accuracy",f1_score(predi,y_test))

accuracy 0.8529411764705883


In [15]:
from sklearn.metrics import classification_report
print(classification_report(predi,y_test))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92        62
           1       0.97      0.76      0.85        38

    accuracy                           0.90       100
   macro avg       0.92      0.87      0.89       100
weighted avg       0.91      0.90      0.90       100

